### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [CountNick/frontend-data#1]
Hi Nick, je code ziet er prima uit, ik zou gezien je voortgang me nu even richten op het afmaken van de applicatie, en als je tijd over hebt de styling aanpassen. In jouw geval zou je nog winst kunnen behalen door je code op te splitsen, zodat niet alles in 1 bestand zit, [zie bijvoorbeeld deze url](https://github.com/StefanGerrits2/frontend-data/tree/master/modules). Veel succes!

**Comment by CountNick** [comment]
Thanks voor de feedback! 👍 Wilde dat inderdaad nog wel meenemen, maar helaas geen tijd meer voor gehad.
