### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by WesselSmit** [CountNick/frontend-data#2]
# Wat mist er nog?
- [ ] zet files zoals `.gitignore` in de `.gitignore`
- [x] add description
- [x] zet bij concept een link naar de totale uitleg in de wiki
- [x] link naar gebruikte d3 code/voorbeeld
- [x] leg uit wat je doet met grote/lage/lege waardes
- [x] leg uit wat je daadwerkelijk ophaalt in je sparql query zodat de gebruiker dit niet hoeft te lezen en geen verstand van sparql hoeft te hebben
- [x] add plagiarism and acknowledgements (zet credits in readme)
* add uitleg over:
    - [x] update pattern
    - [ ] cleaning/transforming pattern
- [x] leg uit wat de doelgroep is
- [x] leg uit hoe de data/vis verandert aan de hand van interactie

# Voorgestelde veranderingen?
* maak gebruik van modules voor meer overzicht
* zet sparql query in een <details> zodat je het kan in-/uitklappen
* verander de assen in de visualisatie aan de hand van de data
* gebruik bij de update functie `merge()` of een combinatie van `exit()` `remove()` `enter()`
     * Nu verwijder je alles en bouw je het opnieuw op met nieuwe data, maar je kan beter de bestaande elementen opnieuw gebruiken

# Wat is er al erg goed?
* visualisatie is duidelijk en spreekt voor zich
* juiste assen zijn gebruikt]
* gebruiker kan conclusies aan de hand van de visualisatie trekken
* code is te volgen en maakt goed gebruik van meaningful comments

**Comment by CountNick** [comment]
gitignore is not something you want to ignore: https://stackoverflow.com/questions/10176875/add-gitignore-to-gitignore/10177000

**Comment by CountNick** [comment]
Fixed most of the issues
